=== Izazkhan/xml-parser/builds/storage/catalog.dtd
<!ELEMENT catalog (item)+>
<!ELEMENT item (entity_id,CategoryName,sku,name,description,shortdesc,price,link,image,Brand,Rating,CaffeineType,Count,Flavored,Seasonal,Instock,Facebook,IsKCup)>
<!ELEMENT entity_id (#PCDATA)>
<!ELEMENT CategoryName (#PCDATA)>
<!ELEMENT sku (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description EMPTY>
<!ELEMENT shortdesc (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT Brand (#PCDATA)>
<!ELEMENT Rating (#PCDATA)>
<!ELEMENT CaffeineType (#PCDATA)>
<!ELEMENT Count (#PCDATA)>
<!ELEMENT Flavored (#PCDATA)>
<!ELEMENT Seasonal (#PCDATA)>
<!ELEMENT Instock (#PCDATA)>
<!ELEMENT Facebook (#PCDATA)>
<!ELEMENT IsKCup (#PCDATA)>

=== Izazkhan/xml-parser/storage/coffee-feed-valid.xml
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog>
  <item>
    <entity_id>340</entity_id>
    <CategoryName>
      <![CDATA[ Green Mountain Ground Coffee ]]>
    </CategoryName>
    <sku>20</sku>
    <name>
      <![CDATA[ Green Mountain Coffee French Roast Ground Coffee 24 2.2oz Bag ]]>
    </name>
    <description/>
    <shortdesc>
      <![CDATA[ Green Mountain Coffee French Roast Ground Coffee 24 2.2oz Bag steeps cup after cup of smoky-sweet, complex dark roast coffee from Green Mountain Ground Coffee. ]]>
    </shortdesc>
    <price>41.6000</price>
    <link>http://www.coffeeforless.com/green-mountain-coffee-french-roast-ground-coffee-24-2-2oz-bag.html</link>
    <image>http://mcdn.coffeeforless.com/media/catalog/product/images/uploads/intro/frac_box.jpg</image>
    <Brand>
      <![CDATA[ Green Mountain Coffee ]]>
    </Brand>
    <Rating>0</Rating>
    <CaffeineType>Caffeinated</CaffeineType>
    <Count>24</Count>
    <Flavored>No</Flavored>
    <Seasonal>No</Seasonal>
    <Instock>Yes</Instock>
    <Facebook>1</Facebook>
    <IsKCup>0</IsKCup>
  </item>
  <item>
    <entity_id>6926</entity_id>
    <CategoryName>
      <![CDATA[ New Products ]]>
    </CategoryName>
    <sku>6336C</sku>
    <name>
      <![CDATA[ Green Mountain Coffee Toasted Marshmallow Mocha K-cup Pods 96ct ]]>
    </name>
    <description/>
    <shortdesc>
      <![CDATA[ Green Mountain Coffee Toasted Marshmallow Mocha K-cup Pods 96ct is like drinking a smores right from the fire place. Transport yourself back the holidays with this delicious coffee treat. ]]>
    </shortdesc>
    <price>59.9600</price>
    <link>http://www.coffeeforless.com/green-mountain-coffee-toasted-marshmallow-mocha-k-cup-pods-96ct.html</link>
    <image>http://mcdn.coffeeforless.com/media/catalog/product//g/r/green-montain-toasted-marshmallow-mocha-kcup-pods_1.jpg</image>
    <Brand>
      <![CDATA[ Green Mountain Coffee ]]>
    </Brand>
    <Rating>5</Rating>
    <CaffeineType>Caffeinated</CaffeineType>
    <Count>96</Count>
    <Flavored>Yes</Flavored>
    <Seasonal>Yes</Seasonal>
    <Instock>Yes</Instock>
    <Facebook>0</Facebook>
    <IsKCup>1</IsKCup>
  </item>
</catalog>
